version: '3.8'

services:
  web:
    build: .
    command: gunicorn kmsite.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env-dev-postgres
    depends_on:
      - db
  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker-postgres:/docker-entrypoint-initdb.d/
    env_file:
      - ./env-dev-postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "kitamanager", "-U", "kitamanager" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
