#!/bin/bash
set -eux

export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $KITAMANAGER_DB_USER WITH PASSWORD '$KITAMANAGER_DB_PASSWORD';
  CREATE DATABASE $KITAMANAGER_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $KITAMANAGER_DB_NAME TO $KITAMANAGER_DB_USER;
EOSQL
