# Generated by Django 5.0 on 2023-12-07 09:51

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [BtreeGistExtension()]
